version: '3'
services: 
  postgres:
    image: 'postgres:latest'
  redis:
    image: 'redis:latest'
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./server
    volumes: 
      - /app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis # goes to our redis service for it
      - REDIS_PORT=6379 #default port on redis docs
      - PGUSER=postgres
      - PGHOST=postgres #our service name
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password #default password for postgres according to docs
      - PGPORT=5432 #EXPOSE 5432  based on postgres docs
  client:
    build: 
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis # goes to our redis service for it
      - REDIS_PORT=6379 #default port on redis docs
  nginx: 
    restart: always ## need to make sure it needs to up always time since its routing traffic
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'

      